# Name your workflow. 
name: hello-world 
# Set the trigger for the workflow
on: push
# This trigger states the push event runs the workflow when you push a commmit or tag, or when create a responsitory from a template.
# Define a job  what happend when the workflow runs
jobs:
  hello-world-job:
    #specify a runner. A runner is a machine that executes the jobs in a workflow. There are two basic types of runners available: GitHub-hosted runners and self-hosted runners.
    runs-on: ubuntu-latest
# Add a step to run your first action. As we mentioned before, each job is made up of one or more steps. 
    steps: 
      - name: Check out repository code #First, we define a name for our step. 
        uses: actions/checkout@v3 # Next, uses: actions/checkout@v3 specifies that this step will use @v3 of the checkout action.
        run: echo "$(cat hello_world.txt)" #add a step to run a bash script that echoes our Hello World!
